### ISSUE TITLE
Lightning Tweaks doesn't handle Cubic Chunks style worlds well.

### ISSUE THREAD

**Issue by border999** [JamieBrassel/Lightning-Tweaks#1]
[crash-2020-04-30_14.06.59-server.txt](https://github.com/JamieBrassel/Lightning-Tweaks/files/4561968/crash-2020-04-30_14.06.59-server.txt)

**Comment by JamieBrassel** [comment]
Lightning Tweaks for Minecraft 1.12.2 is no longer actively developed. All new updates will apply only to 1.15.x.
